/*!
@file       ScriptingAPI.cpp
@author     Ng Wei Jie (weijie.ng) 100%
@date       06/11/2025
@brief		Implements the scripting system for native C++ hot-reloadable
			components. Handles class scanning, code generation, compilation,
			dynamic library loading/unloading, and script lifecycle updates.

Copyright (C) 2026 DigiPen Institute of Technology. All rights reserved.
/*________________________________________________________________________*/
#include "pch.h"
#include "ScriptingAPI.h"
#include "Components.h"
#include "UpdateStackManager.h"
#ifdef PLATFORM_WINDOWS
#define RESERVED_NATIVE 100

static HMODULE hDll;
static std::string CompileCmd;

/*!
* \brief
*   Generates a NativeScriptLoader.cpp file containing component registration
*   and unregistration code for discovered script classes.
* \param
*   var - vector of class names and their reflected UPROPERTY fields
* \param
*   classdir - vector of file paths where each class is defined
*/
#define UNUSED_PARAMETER(x) (void)(x)
void generateCodeForClass(std::vector<std::pair<std::string, std::vector<std::string>>> var, std::vector<std::string> classdir)
{
	UNUSED_PARAMETER(classdir);
	std::ofstream os("../../../src/Scripts/NativeScriptLoader.cpp");



	if (!os.is_open())
	{
		std::cerr << "error cannot open Script Loader file" << std::endl;
		return;
	}
	std::string stringtocopy = R"(

/*!
@file       NativeScriptLoader.cpp
@author     Auto-generated by ScriptingAPI (Ng Wei Jie)
@date       06/11/2025
@brief		Automatically generated source file that registers all discovered
			native script components with the ECS and reflection system. 
			This file is regenerated whenever scripts are recompiled and 
			should not be edited manually.

Copyright (C) 2026 DigiPen Institute of Technology. All rights reserved.
/*________________________________________________________________________*/

#include "NativeScriptLoader.h"

)";

	os << stringtocopy;
	for (std::pair<std::string, std::vector<std::string>> value : var)
		os << "#include \"" << value.first << ".h\"\n";



	stringtocopy = R"(

/*!
* \brief
*   Initializes all native script components and links shared systems such as 
*   Input and Savestate to the reflection map.
* \param
*   registry - ECS registry instance
* \param
*   componentRegistry - global component registry
* \param
*   typeMap - shared reflection type map
* \param
*   input - pointer to global input manager
* \param
*   ss - pointer to savestate instance
*/
void NativeComponentInitialise(Registry& registry, ComponentRegistry& componentRegistry, std::unordered_map<std::string, rtr::TypeInfo>* typeMap, Input* input, CEO* ceo)
{
	CEO::Instance().SetInstance(ceo);
	rtr::SetSharedMap(typeMap);
	if(!Input::GetInstance())
		Input::SetInstance(input);
	if (!Input::GetInstance()) std::cout << "deleted input pointer";


        )";




	os << stringtocopy;

	for (std::pair<std::string, std::vector<std::string>> value : var)
	{
		os << "RegisterNativeComponentMacro(" << value.first << ");\n";
	}

	os << " \n}\n";



	stringtocopy = R"( 
/*!
* \brief
*   Clears and unregisters all native script components from the ECS and
*   removes their corresponding component storages from the registry.
* \param
*   registry - ECS registry instance
* \param
*   componentRegistry - global component registry
*/
void NativeComponentClear(Registry& registry,ComponentRegistry& componentRegistry)
{
)";
	os << stringtocopy;
	for (std::pair<std::string, std::vector<std::string>> value : var)
	{
		//os << "CEO::Instance().GetManager<Savestate>()->RemoveComponentCast<ComponentStorage<" << value.first << ">>();\n";

		os << "componentRegistry.UnregisterComponent(\"" << value.first << "\");\n";

		os << "registry.EraseComponentStorage(std::type_index(typeid(" << value.first << ")));\n";

	}

	os << " }\n";
}

/*!
* \brief
*   Scans the specified directory for header files defining script classes that
*   inherit from ScriptInstance. Extracts class names and UPROPERTY fields.
* \param
*   directoryPath - path to search for C++ script header files
*/
void ScanDirectoryForClasses(const char* directoryPath)
{

	std::regex classRegex(R"(class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*public\s+ScriptInstance)");
	std::regex propertyREGEX(R"(UPROPERTY)");


	std::vector<std::pair<std::string, std::vector<std::string>>> ClassesAndProperties;
	std::vector<std::string> classdirVec;
	for (const auto& entry : std::filesystem::recursive_directory_iterator(directoryPath))
	{
		if (entry.is_regular_file() && entry.path().extension() == ".h")
		{
			std::ifstream file(entry.path());
			std::string line;

			if (!file.is_open()) {
				std::cerr << "Failed to open: " << entry.path() << std::endl;
				continue;
			}
			std::cout << "Opened: " << entry.path() << std::endl;
			std::vector<std::string>Properties;
			std::string className;
			std::string classDir;

			while (std::getline(file, line))
			{
				std::smatch propmatch;

				if (std::regex_search(line, propmatch, propertyREGEX) && !className.empty())
				{
					std::cout << "found UPROPERTY" << std::endl;
					std::string nextLine;
					if (std::getline(file, nextLine))
					{
						// Optional: strip leading/trailing whitespace
						std::istringstream iss(nextLine);
						std::string name;
						//skips first word
						iss >> name;

						iss >> name;
						std::cout << "found type:" << name << std::endl;
						name.erase(std::remove(name.begin(), name.end(), ';'), name.end());
						Properties.push_back(name);

					}
				}
				std::smatch match;
				if (std::regex_search(line, match, classRegex))
				{
					// Extract class name from regex match className = match[1];
					std::cout << "Found class: " << className << " in " << entry.path() << "\n";
					className = match[1];
					classDir = entry.path().string();
					
					// Generate code for the class (this part can use RTTR or your own logic)
				}


			}
			if (!className.empty())
			{
				ClassesAndProperties.emplace_back(std::make_pair(className, Properties));
				std::filesystem::create_directory("Assets/Scripts/");
				std::string Assets = "Assets/Scripts/" + className + ".Script";
				std::ofstream ofs(Assets);



				classdirVec.emplace_back(classDir);
				className.clear();
				classDir.clear();
			}
		}
	}

	generateCodeForClass(ClassesAndProperties, classdirVec);

}


/*!
* \brief
*   Compiles the Scripts project and loads the generated DLL into memory.
*   Invokes scanning and code generation for any new classes.
* \param
*   directoryPath - path to scan for class definitions
* \param
*   registry - ECS registry
* \param
*   componentRegistry - global component registry
* \param
*   typeMap - reflection type map for runtime type registration
* \param
*   input - input system instance
* \param
*   ss - pointer to savestate instance
*/
void CompileScript(const char* directoryPath, Registry& registry, ComponentRegistry& componentRegistry, std::unordered_map<std::string,
	rtr::TypeInfo>* typeMap, Input* input, CEO* ceo)
{
	ScanDirectoryForClasses(directoryPath);

#if _DEBUG
	CompileCmd =
		"call \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" && "
		"msbuild ../Scripts/Scripts.vcxproj "
		"/p:TargetName=Scripts "
		"/p:Configuration=Debug "
		"/p:Platform=x64 ";
#else
	CompileCmd =
		"call \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" && "
		"msbuild ../Scripts/Scripts.vcxproj /p:TargetName=Scripts /p:Configuration=Release /p:Platform=x64 ";
#endif



	int result = system(CompileCmd.c_str());

	if (result == 0)
	{
		printf("Compilation succeeded!\n");


#if _DEBUG
		system("copy \"..\\Scripts\\Debug\\Scripts.dll\" \"..\\Debug\\Scripts.dll\"");

#else
		system("copy \"..\\Scripts\\Release\\Scripts.dll\" \"..\\Release\\Scripts.dll\"");

#endif
	}
	else
		printf("Compilation failed with code %d\n", result);


	LoadScript(registry, componentRegistry, typeMap, input, ceo);
}


void HandleMSBuildOutput(std::string line)
{
	// --- 1. Trim newline ---
	if (!line.empty() && (line.back() == '\n' || line.back() == '\r'))
		line.pop_back();
	if (line.size() > 2000) { LOGE("word count exceeded console buffer size!!"); return; }
	// --- 2. Determine log level ---
	Logger::LogLevel level = Logger::LogLevel::Info;

	// make a lowercase copy for comparison
	std::string lower = line;
	std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);

	// MSBuild typically includes "error" or "warning" in the line
	if (lower.find("error(s)") != std::string::npos && lower.find("0 error(s)") == std::string::npos)
		CEO::Instance().GetManager<ResourceManager>()->GetAudio("faaah.mp3").Play();

	if (lower.find("error") != std::string::npos)
		level = Logger::LogLevel::Error;
	else if (lower.find("warning") != std::string::npos)
		level = Logger::LogLevel::Warning;

	// --- 3. Send to logger (which stacks duplicates automatically) ---
	CEO::Instance().GetManager<Logger>()->AddLog(line, level);
}


/*!
* \brief
*   Recompiles and reloads the Scripts DLL during runtime. Handles
*   entity cleanup, storage reset, and dynamic re-registration of components.
* \param
*   directoryPath - path to scan for class definitions
* \param
*   registry - ECS registry
* \param
*   componentRegistry - global component registry
* \param
*   typeMap - reflection type map
* \param
*   input - input system instance
* \param
*   ss - pointer to savestate instance
*/
#define UNUSED_PARAMETER(x) (void)(x)
void RecompileScript(const char* directoryPath, Registry& registry, ComponentRegistry& componentRegistry,
	std::unordered_map<std::string, rtr::TypeInfo>* typeMap, Input* input,
	CEO* ss)
{

	ScanDirectoryForClasses(directoryPath);

	/*	int result2 = system("cmake -S \"../../../src/NativeScripting/\" -B \"../../../build\"");
	if (result2 != 0) {
		std::cerr << "CMake configuration failed with code " << result2 << std::endl;
	}*/

#if _DEBUG
	CompileCmd =
		"call \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" && "
		"msbuild ../Scripts/Scripts.vcxproj "
		"/p:TargetName=Scripts "
		"/p:Configuration=Debug "
		"/p:Platform=x64 ";

#else

	CompileCmd =
		"call \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\" && "
		"msbuild ../Scripts/Scripts.vcxproj "
		"/p:TargetName=Scripts "
		"/p:Configuration=Release "
		"/p:Platform=x64 ";

#endif

	auto entities = registry.GetEntitiesWithComponents<NativeScriptingComponent>();
	for (auto ent : entities)
	{
		auto Native = registry.GetComponent<NativeScriptingComponent>(ent);
		for (auto& [name, Instance] : Native->scripts)
		{
			if (Instance.Instance)
			{
				Instance.OnDeleteScript(Instance);
			}
		}
	}
	//CEO::Instance().GetManager<Savestate>()->StartOriginal();
	//CEO::Instance().GetManager<Savestate>()->ClearState();

	registry.ClearAllComponentStorages();
	registry.DestroyAllEntities();
	registry.RestartEntityCount();

	FreeScript(registry, componentRegistry);

#if _DEBUG

	try {
		std::filesystem::copy_file("../Scripts/Debug/Scripts.dll",
			"../Scripts/Debug/Scripts_old.dll",
			std::filesystem::copy_options::overwrite_existing);
		std::filesystem::rename("../Scripts/Debug/Scripts.pdb",
			"../Scripts/Debug/Scripts_old.pdb");
		std::filesystem::copy_file("../Scripts/Debug/Scripts_old.pdb",
			"../Scripts/Debug/Scripts.pdb",
			std::filesystem::copy_options::overwrite_existing);
	}
	catch (std::filesystem::filesystem_error& e) {
		std::cout << e.what() << '\n';
	}
#else
	try {
		std::filesystem::copy_file("../Scripts/Release/Scripts.dll",
			"../Scripts/Release/Scripts_old.dll",
			std::filesystem::copy_options::overwrite_existing);
		std::filesystem::rename("../Scripts/Release/Scripts.pdb",
			"../Scripts/Release/Scripts_old.pdb");
		std::filesystem::copy_file("../Scripts/Release/Scripts_old.pdb",
			"../Scripts/Release/Scripts.pdb",
			std::filesystem::copy_options::overwrite_existing);
	}
	catch (std::filesystem::filesystem_error& e) {
		std::cout << e.what() << '\n';
	}
#endif


	HMODULE hCheck = GetModuleHandleA("Scripts.dll");
	if (hCheck)
		std::cout << "Still loaded in process!\n";
	else
		std::cout << "DLL fully unloaded.\n";
	//int result = system(CompileCmd.c_str());
	//UNUSED_PARAMETER(result);

	FILE* pipe = _popen(CompileCmd.c_str(), "r");
	if (!pipe)
	{
		LOGE("Failed to run MSBuild");
	}
	else
	{
		char buffer[2048];
		while (fgets(buffer, sizeof(buffer), pipe))
		{
			HandleMSBuildOutput(buffer);  // classify + collapse
		}

		_pclose(pipe);
	}



	system("echo Current directory: %cd%");

#if _DEBUG
	system("copy \"..\\Scripts\\Debug\\Scripts.dll\" \"..\\Debug\\Scripts.dll\"");

#else
	system("copy \"..\\Scripts\\Release\\Scripts.dll\" \"..\\Release\\Scripts.dll\"");

#endif

	//std::this_thread::sleep_for(std::chrono::seconds(3));


	


	LoadScript(registry, componentRegistry, typeMap, input, ss);


}


/*!
* \brief
*   Dynamically loads the compiled Scripts.dll and initializes all
*   native script components defined within.
* \param
*   registry - ECS registry instance
* \param
*   componentRegistry - global component registry
* \param
*   typeMap - reflection type map for runtime type registration
* \param
*   input - input system instance
* \param
*   ss - pointer to savestate instance
*/
void LoadScript(Registry& registry, ComponentRegistry& componentRegistry,
	std::unordered_map<std::string, rtr::TypeInfo>* typeMap, Input* input, CEO* ceo)
{

	hDll = LoadLibraryA("Scripts.dll");
	if (!hDll)
	{
		std::cerr << "Failed to load DLL bruh\n";
		return;
	}

	using NativeComponentInitialise = void(*)(Registry&, ComponentRegistry&, std::unordered_map<std::string, rtr::TypeInfo>*
		, Input* input, CEO*);
	NativeComponentInitialise ProcessData = reinterpret_cast<NativeComponentInitialise>(
		GetProcAddress(hDll, "NativeComponentInitialise")
		);
	if (!ProcessData)
	{
		std::cerr << "Failed to locate initialise function!" << std::endl;
		FreeLibrary(hDll);
		return;
	}
	ProcessData(registry, componentRegistry, typeMap, input, ceo);
}

/*!
* \brief
*   Frees all entities and unloads the currently loaded Scripts.dll
*   from memory.
* \param
*   registry - ECS registry
* \param
*   componentRegistry - global component registry
*/
void FreeScript(Registry& registry, ComponentRegistry& componentRegistry)
{

	DeleteScriptInstance(registry, componentRegistry);


	using NativeComponentDestroy = void(*)(Registry&, ComponentRegistry&);
	NativeComponentDestroy NativeComponentClear = reinterpret_cast<NativeComponentDestroy>(
		GetProcAddress(hDll, "NativeComponentClear")
		);

	if (!NativeComponentClear)
	{
		std::cerr << "Failed to locate clear function!" << std::endl;
		FreeLibrary(hDll);
		return;
	}
	NativeComponentClear(registry, componentRegistry);


	if (!FreeLibrary(hDll)) {
		DWORD err = GetLastError();
		std::cerr << "FreeLibrary failed. Error code: " << err << std::endl;
	}
	else {
		std::cout << "DLL unloaded successfully." << std::endl;
	}



}



#endif
void OnStartCall_Safe(
        NativeScriptingComponent::ScriptEntry* inst,
        Registry* reg
)
{
#ifdef	EditorFlag

    __try {
#endif
            inst->OnStartFunction(inst->Instance, *reg);
#ifdef	EditorFlag

    }
    __except (EXCEPTION_EXECUTE_HANDLER) {


    // keep it tiny: avoid anything that might allocate
        inst->state = NativeScriptingComponent::ScriptState::Faulted; // if you have this
        // maybe set a flag and log later outside SEH

    }
#endif
}
#define UNUSED_PARAM(P) (void)P
void CreateScriptInstance(Registry& registry, ComponentRegistry& componentRegistry)
{
	UNUSED_PARAM(componentRegistry);


	auto entities = registry.GetEntitiesWithComponents<NativeScriptingComponent>();
	for (auto ent : entities)
	{

		auto& Native = *registry.GetComponent<NativeScriptingComponent>(ent);

		for (auto& [name, Instance] : Native.scripts)
		{

			if (!Instance.Instance)
			{
				Instance.OnCreateScript(Instance);

			}
			else
			{
				if (!Instance.isStarted)
				{
					Instance.isStarted = true;
					Instance.Instance->entity = ent;
					
					Instance.BindFrom(Instance.Instance);

					OnStartCall_Safe(&Instance, &registry);
					Instance.BindTo(Instance.Instance);

					//Instance.OnStartFunction(Instance.Instance, registry);
					if (Instance.state == NativeScriptingComponent::ScriptState::Faulted)
					{
						LOGE("Error in %s OnStart(): ", name.c_str());
					}
				}
			}
		}

	}
}
#undef UNUSED_PARAM


void OnFixedUpdateCall_Safe(
	NativeScriptingComponent::ScriptEntry* inst,
	Registry* reg,float dt,bool* firstframe
)
{
#ifdef	EditorFlag
	__try {
#endif

    inst->OnFixedUpdateFunction(inst->Instance, *reg,dt, *firstframe);
#ifdef	EditorFlag
}
	__except (EXCEPTION_EXECUTE_HANDLER) {


		// keep it tiny: avoid anything that might allocate
		inst->state = NativeScriptingComponent::ScriptState::Faulted; // if you have this
		// maybe set a flag and log later outside SEH

	}
#endif

    }
/*!
* \brief
*   Calls the OnFixedUpdate function of all active native scripts.
* \param
*   registry - ECS registry
* \param
*   componentRegistry - global component registry
* \param
*   dt - fixed time step delta
* \param
*   firstframe - flag indicating first frame of execution
*/
void FixedUpdateScriptInstance(Registry& registry, ComponentRegistry&, float dt, bool& firstframe)
{
	auto entities = registry.GetEntitiesWithComponents<NativeScriptingComponent>();

	UpdateStackManager* usm = CEO::Get<UpdateStackManager>();
	for (auto ent : entities)
	{
		if (usm->ShouldNotUpdate(ent)) continue;
		if (!usm->IsActive(ent)) continue;

		NativeScriptingComponent& Native = *registry.GetComponent<NativeScriptingComponent>(ent);
		for (auto& [name, Instance] : Native.scripts)
		{
			if (Instance.isStarted)
			{
				if (Instance.state == NativeScriptingComponent::ScriptState::Faulted)
				{
					LOGE("Error in %s OnFixedUpdate(): ", name.c_str());
					continue;
				}
				Instance.BindFrom(Instance.Instance);
				OnFixedUpdateCall_Safe(&Instance, &registry,dt,&firstframe);
				Instance.BindTo(Instance.Instance);

			}

		}
	}
}

void OnUpdateCall_Safe(
	NativeScriptingComponent::ScriptEntry* inst,
	Registry* reg, float dt, bool* firstframe
)
{
#ifdef	EditorFlag

    __try {
#endif

		inst->OnUpdateFunction(inst->Instance, *reg, dt, *firstframe);
#ifdef	EditorFlag

    }
	__except (EXCEPTION_EXECUTE_HANDLER) {


		// keep it tiny: avoid anything that might allocate
		inst->state = NativeScriptingComponent::ScriptState::Faulted; // if you have this
		// maybe set a flag and log later outside SEH


	}
#endif

}
/*!
* \brief
*   Updates all active native scripts each frame by invoking their OnUpdate
*   or OnStart callbacks as needed.
* \param
*   registry - ECS registry
* \param
*   componentRegistry - global component registry
* \param
*   dt - frame delta time
* \param
*   firstframe - flag indicating first frame of execution
*/
void UpdateScriptInstance(Registry& registry, ComponentRegistry& , float dt, bool& firstframe)
{
	auto entities = registry.GetEntitiesWithComponents<NativeScriptingComponent>();

	UpdateStackManager* usm = CEO::Get<UpdateStackManager>();
	for (auto ent : entities)
	{
		if (usm->ShouldNotUpdate(ent)) continue;
		if (!usm->IsActive(ent)) continue;

		NativeScriptingComponent& Native = *registry.GetComponent<NativeScriptingComponent>(ent);
		for (auto& [name, Instance] : Native.scripts)
		{
			if (Instance.isStarted)
			{
				if (Instance.state == NativeScriptingComponent::ScriptState::Faulted)
				{
					LOGE("Error in %s OnUpdate(): ", name.c_str());
					continue;
				}
				Instance.BindFrom(Instance.Instance);
				OnUpdateCall_Safe(&Instance, &registry, dt, &firstframe);
				Instance.BindTo(Instance.Instance);
			}
		}
		firstframe = false;

	}
}

/*!
* \brief
*   Deletes all existing script instances and clears registered scripts
*   from all NativeScriptingComponents.
* \param
*   registry - ECS registry
* \param
*   componentRegistry - global component registry
*/
void DeleteScriptInstance(Registry& registry, ComponentRegistry&)
{
	auto entities = registry.GetEntitiesWithComponents<NativeScriptingComponent>();
	for (auto ent : entities)
	{
		auto Native = registry.GetComponent<NativeScriptingComponent>(ent);
		for (auto& [name, Instance] : Native->scripts)
		{
			if (Instance.Instance)
			{
				Instance.OnDeleteScript(Instance);
			}
		}
	}

}
#undef UNUSED_PARAMETER
