

/*!
@file       NativeScriptLoader.cpp
@author     Auto-generated by ScriptingAPI (Ng Wei Jie)
@date       06/11/2025
@brief		Automatically generated source file that registers all discovered
			native script components with the ECS and reflection system. 
			This file is regenerated whenever scripts are recompiled and 
			should not be edited manually.

Copyright (C) 2026 DigiPen Institute of Technology. All rights reserved.
/*________________________________________________________________________*/

#include "NativeScriptLoader.h"

#include "AudioLinker.h"
#include "AudioSliderScript.h"
#include "AuraScript.h"
#include "BackToMapScript.h"
#include "BlindManipulationScript.h"
#include "CameraControllerScript.h"
#include "ChangeScene.h"
#include "CollisionCallbackTestScript.h"
#include "ConfirmSceneScript.h"
#include "DialogueScript.h"
#include "DoorManipulationScript.h"
#include "EnemyCollisionScript.h"
#include "EnemyInitScript.h"
#include "EnemySpawnerScript.h"
#include "EnemyStatusEffectScript.h"
#include "ExitButtonScript.h"
#include "EyeCollisionScript.h"
#include "FadeScript.h"
#include "FlashingVFX.h"
#include "GameobjectPoolScript.h"
#include "GameStateManagerScript.h"
#include "GodModeScript.h"
#include "HealthbarScript.h"
#include "HealthScript.h"
#include "InitScript.h"
#include "ItemCardScript.h"
#include "ItemIconManager.h"
#include "ItemMenuManager.h"
#include "LandingPageScript.h"
#include "LarvaProjectileScript.h"
#include "LightFlickerScript.h"
#include "LuckItemScript.h"
#include "MapButtonManagerScript.h"
#include "MapSpawner.h"
#include "MenuManagerScript.h"
#include "MinimapScript.h"
#include "OnboardingGameScript.h"
#include "OnboardingScript.h"
#include "ParticleScript.h"
#include "PauseManagerScript.h"
#include "PlayerControllerScript.h"
#include "PopupManagerScript.h"
#include "PostProcessToggleScript.h"
#include "ProjectileScript.h"
#include "RotateController.h"
#include "ShootScript.h"
#include "SimpleAudioScript.h"
#include "StackTestScript.h"
#include "StampManagerScript.h"
#include "TileManagerScript.h"
#include "TreasureChestScript.h"
#include "UpdateStatViewScript.h"
#include "VideoTest.h"
#include "WaveTransitionScript.h"
#include "WinColliderScript.h"


/*!
* \brief
*   Initializes all native script components and links shared systems such as 
*   Input and Savestate to the reflection map.
* \param
*   registry - ECS registry instance
* \param
*   componentRegistry - global component registry
* \param
*   typeMap - shared reflection type map
* \param
*   input - pointer to global input manager
* \param
*   ss - pointer to savestate instance
*/
void NativeComponentInitialise(Registry& registry, ComponentRegistry& componentRegistry, std::unordered_map<std::string, rtr::TypeInfo>* typeMap, Input* input, CEO* ceo)
{
	CEO::Instance().SetInstance(ceo);
	rtr::SetSharedMap(typeMap);
	if(!Input::GetInstance())
		Input::SetInstance(input);
	if (!Input::GetInstance()) std::cout << "deleted input pointer";


        RegisterNativeComponentMacro(AudioLinker);
RegisterNativeComponentMacro(AudioSliderScript);
RegisterNativeComponentMacro(AuraScript);
RegisterNativeComponentMacro(BackToMapScript);
RegisterNativeComponentMacro(BlindManipulationScript);
RegisterNativeComponentMacro(CameraControllerScript);
RegisterNativeComponentMacro(ChangeScene);
RegisterNativeComponentMacro(CollisionCallbackTestScript);
RegisterNativeComponentMacro(ConfirmSceneScript);
RegisterNativeComponentMacro(DialogueScript);
RegisterNativeComponentMacro(DoorManipulationScript);
RegisterNativeComponentMacro(EnemyCollisionScript);
RegisterNativeComponentMacro(EnemyInitScript);
RegisterNativeComponentMacro(EnemySpawnerScript);
RegisterNativeComponentMacro(EnemyStatusEffectScript);
RegisterNativeComponentMacro(ExitButtonScript);
RegisterNativeComponentMacro(EyeCollisionScript);
RegisterNativeComponentMacro(FadeScript);
RegisterNativeComponentMacro(FlashingVFX);
RegisterNativeComponentMacro(GameobjectPoolScript);
RegisterNativeComponentMacro(GameStateManagerScript);
RegisterNativeComponentMacro(GodModeScript);
RegisterNativeComponentMacro(HealthbarScript);
RegisterNativeComponentMacro(HealthScript);
RegisterNativeComponentMacro(InitScript);
RegisterNativeComponentMacro(ItemCardScript);
RegisterNativeComponentMacro(ItemIconManager);
RegisterNativeComponentMacro(ItemMenuManager);
RegisterNativeComponentMacro(LandingPageScript);
RegisterNativeComponentMacro(LarvaProjectileScript);
RegisterNativeComponentMacro(LightFlickerScript);
RegisterNativeComponentMacro(LuckItemScript);
RegisterNativeComponentMacro(MapButtonManagerScript);
RegisterNativeComponentMacro(MapSpawner);
RegisterNativeComponentMacro(MenuManagerScript);
RegisterNativeComponentMacro(MinimapScript);
RegisterNativeComponentMacro(OnboardingGameScript);
RegisterNativeComponentMacro(OnboardingScript);
RegisterNativeComponentMacro(ParticleScript);
RegisterNativeComponentMacro(PauseManagerScript);
RegisterNativeComponentMacro(PlayerControllerScript);
RegisterNativeComponentMacro(PopupManagerScript);
RegisterNativeComponentMacro(PostProcessToggleScript);
RegisterNativeComponentMacro(ProjectileScript);
RegisterNativeComponentMacro(RotateController);
RegisterNativeComponentMacro(ShootScript);
RegisterNativeComponentMacro(SimpleAudioScript);
RegisterNativeComponentMacro(StackTestScript);
RegisterNativeComponentMacro(StampManagerScript);
RegisterNativeComponentMacro(TileManagerScript);
RegisterNativeComponentMacro(TreasureChestScript);
RegisterNativeComponentMacro(UpdateStatViewScript);
RegisterNativeComponentMacro(VideoTest);
RegisterNativeComponentMacro(WaveTransitionScript);
RegisterNativeComponentMacro(WinColliderScript);
 
}
 
/*!
* \brief
*   Clears and unregisters all native script components from the ECS and
*   removes their corresponding component storages from the registry.
* \param
*   registry - ECS registry instance
* \param
*   componentRegistry - global component registry
*/
void NativeComponentClear(Registry& registry,ComponentRegistry& componentRegistry)
{
componentRegistry.UnregisterComponent("AudioLinker");
registry.EraseComponentStorage(std::type_index(typeid(AudioLinker)));
componentRegistry.UnregisterComponent("AudioSliderScript");
registry.EraseComponentStorage(std::type_index(typeid(AudioSliderScript)));
componentRegistry.UnregisterComponent("AuraScript");
registry.EraseComponentStorage(std::type_index(typeid(AuraScript)));
componentRegistry.UnregisterComponent("BackToMapScript");
registry.EraseComponentStorage(std::type_index(typeid(BackToMapScript)));
componentRegistry.UnregisterComponent("BlindManipulationScript");
registry.EraseComponentStorage(std::type_index(typeid(BlindManipulationScript)));
componentRegistry.UnregisterComponent("CameraControllerScript");
registry.EraseComponentStorage(std::type_index(typeid(CameraControllerScript)));
componentRegistry.UnregisterComponent("ChangeScene");
registry.EraseComponentStorage(std::type_index(typeid(ChangeScene)));
componentRegistry.UnregisterComponent("CollisionCallbackTestScript");
registry.EraseComponentStorage(std::type_index(typeid(CollisionCallbackTestScript)));
componentRegistry.UnregisterComponent("ConfirmSceneScript");
registry.EraseComponentStorage(std::type_index(typeid(ConfirmSceneScript)));
componentRegistry.UnregisterComponent("DialogueScript");
registry.EraseComponentStorage(std::type_index(typeid(DialogueScript)));
componentRegistry.UnregisterComponent("DoorManipulationScript");
registry.EraseComponentStorage(std::type_index(typeid(DoorManipulationScript)));
componentRegistry.UnregisterComponent("EnemyCollisionScript");
registry.EraseComponentStorage(std::type_index(typeid(EnemyCollisionScript)));
componentRegistry.UnregisterComponent("EnemyInitScript");
registry.EraseComponentStorage(std::type_index(typeid(EnemyInitScript)));
componentRegistry.UnregisterComponent("EnemySpawnerScript");
registry.EraseComponentStorage(std::type_index(typeid(EnemySpawnerScript)));
componentRegistry.UnregisterComponent("EnemyStatusEffectScript");
registry.EraseComponentStorage(std::type_index(typeid(EnemyStatusEffectScript)));
componentRegistry.UnregisterComponent("ExitButtonScript");
registry.EraseComponentStorage(std::type_index(typeid(ExitButtonScript)));
componentRegistry.UnregisterComponent("EyeCollisionScript");
registry.EraseComponentStorage(std::type_index(typeid(EyeCollisionScript)));
componentRegistry.UnregisterComponent("FadeScript");
registry.EraseComponentStorage(std::type_index(typeid(FadeScript)));
componentRegistry.UnregisterComponent("FlashingVFX");
registry.EraseComponentStorage(std::type_index(typeid(FlashingVFX)));
componentRegistry.UnregisterComponent("GameobjectPoolScript");
registry.EraseComponentStorage(std::type_index(typeid(GameobjectPoolScript)));
componentRegistry.UnregisterComponent("GameStateManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(GameStateManagerScript)));
componentRegistry.UnregisterComponent("GodModeScript");
registry.EraseComponentStorage(std::type_index(typeid(GodModeScript)));
componentRegistry.UnregisterComponent("HealthbarScript");
registry.EraseComponentStorage(std::type_index(typeid(HealthbarScript)));
componentRegistry.UnregisterComponent("HealthScript");
registry.EraseComponentStorage(std::type_index(typeid(HealthScript)));
componentRegistry.UnregisterComponent("InitScript");
registry.EraseComponentStorage(std::type_index(typeid(InitScript)));
componentRegistry.UnregisterComponent("ItemCardScript");
registry.EraseComponentStorage(std::type_index(typeid(ItemCardScript)));
componentRegistry.UnregisterComponent("ItemIconManager");
registry.EraseComponentStorage(std::type_index(typeid(ItemIconManager)));
componentRegistry.UnregisterComponent("ItemMenuManager");
registry.EraseComponentStorage(std::type_index(typeid(ItemMenuManager)));
componentRegistry.UnregisterComponent("LandingPageScript");
registry.EraseComponentStorage(std::type_index(typeid(LandingPageScript)));
componentRegistry.UnregisterComponent("LarvaProjectileScript");
registry.EraseComponentStorage(std::type_index(typeid(LarvaProjectileScript)));
componentRegistry.UnregisterComponent("LightFlickerScript");
registry.EraseComponentStorage(std::type_index(typeid(LightFlickerScript)));
componentRegistry.UnregisterComponent("LuckItemScript");
registry.EraseComponentStorage(std::type_index(typeid(LuckItemScript)));
componentRegistry.UnregisterComponent("MapButtonManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(MapButtonManagerScript)));
componentRegistry.UnregisterComponent("MapSpawner");
registry.EraseComponentStorage(std::type_index(typeid(MapSpawner)));
componentRegistry.UnregisterComponent("MenuManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(MenuManagerScript)));
componentRegistry.UnregisterComponent("MinimapScript");
registry.EraseComponentStorage(std::type_index(typeid(MinimapScript)));
componentRegistry.UnregisterComponent("OnboardingGameScript");
registry.EraseComponentStorage(std::type_index(typeid(OnboardingGameScript)));
componentRegistry.UnregisterComponent("OnboardingScript");
registry.EraseComponentStorage(std::type_index(typeid(OnboardingScript)));
componentRegistry.UnregisterComponent("ParticleScript");
registry.EraseComponentStorage(std::type_index(typeid(ParticleScript)));
componentRegistry.UnregisterComponent("PauseManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(PauseManagerScript)));
componentRegistry.UnregisterComponent("PlayerControllerScript");
registry.EraseComponentStorage(std::type_index(typeid(PlayerControllerScript)));
componentRegistry.UnregisterComponent("PopupManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(PopupManagerScript)));
componentRegistry.UnregisterComponent("PostProcessToggleScript");
registry.EraseComponentStorage(std::type_index(typeid(PostProcessToggleScript)));
componentRegistry.UnregisterComponent("ProjectileScript");
registry.EraseComponentStorage(std::type_index(typeid(ProjectileScript)));
componentRegistry.UnregisterComponent("RotateController");
registry.EraseComponentStorage(std::type_index(typeid(RotateController)));
componentRegistry.UnregisterComponent("ShootScript");
registry.EraseComponentStorage(std::type_index(typeid(ShootScript)));
componentRegistry.UnregisterComponent("SimpleAudioScript");
registry.EraseComponentStorage(std::type_index(typeid(SimpleAudioScript)));
componentRegistry.UnregisterComponent("StackTestScript");
registry.EraseComponentStorage(std::type_index(typeid(StackTestScript)));
componentRegistry.UnregisterComponent("StampManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(StampManagerScript)));
componentRegistry.UnregisterComponent("TileManagerScript");
registry.EraseComponentStorage(std::type_index(typeid(TileManagerScript)));
componentRegistry.UnregisterComponent("TreasureChestScript");
registry.EraseComponentStorage(std::type_index(typeid(TreasureChestScript)));
componentRegistry.UnregisterComponent("UpdateStatViewScript");
registry.EraseComponentStorage(std::type_index(typeid(UpdateStatViewScript)));
componentRegistry.UnregisterComponent("VideoTest");
registry.EraseComponentStorage(std::type_index(typeid(VideoTest)));
componentRegistry.UnregisterComponent("WaveTransitionScript");
registry.EraseComponentStorage(std::type_index(typeid(WaveTransitionScript)));
componentRegistry.UnregisterComponent("WinColliderScript");
registry.EraseComponentStorage(std::type_index(typeid(WinColliderScript)));
 }
